/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include "check.h"
#include "s21_string.h"
#include "string.h"

START_TEST(s21sprintf) {
#line 5
  char str1[1000];
  char str2[1000];
  char *format =
      "% -15.10dEND%- 5dEND%+-5iEND%-5d% 5dEND "
      "%hdEND%-+15ldEND%uEND%uEND%uEND% uEND%+uEND%-12u%f%10f%0f% "
      "f%-f%-10f%10.10f%-10.10f%+10.10f%+f%hf%lf%1f%-0.1f%+0.1f%+ "
      "f%.0f%.2s%-5c%5c%10.10s%hu%c%s%10s%-10s";
  int a1 =
      sprintf(str1, format, 15, -123, 9, -1, 10, 900000000000, 900000000000, 10,
              -9, 900000000000, 10, -9, 900000000000, -5.999, -5.999, -5.999,
              -5.999, -5.999, -5.999, -5.999, -5.999, -5.999, -5.999, -5.999,
              -5.999, -5.999, -5.999, -5.999, -5.999, -5.999, "bruh0", '1', 'b',
              "123", 4294967, 'a', "hello", "hello", "hello");

  int a2 = s21_sprintf(str2, format, 15, -123, 9, -1, 10, 900000000000,
                       900000000000, 10, -9, 900000000000, 10, -9, 900000000000,
                       -5.999, -5.999, -5.999, -5.999, -5.999, -5.999, -5.999,
                       -5.999, -5.999, -5.999, -5.999, -5.999, -5.999, -5.999,
                       -5.999, -5.999, -5.999, "bruh0", '1', 'b', "123",
                       4294967, 'a', "hello", "hello", "hello");

  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(a1, a2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21sprintf);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
